# Generated by Django 5.2.12 on 2026-03-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_window_minutes', models.PositiveIntegerField(default=5, help_text='Extend auction if a trigger event occurs within this many minutes of close.')),
                ('extension_minutes', models.PositiveIntegerField(default=5, help_text='Number of minutes to add when extending.')),
                ('trigger_type', models.CharField(choices=[('ANY_BID', 'Any Bid'), ('ANY_RANK_CHANGE', 'Any Rank Change'), ('L1_CHANGE', 'L1 Change')], default='ANY_BID', max_length=20)),
            ],
            options={
                'db_table': 'auction_configs',
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('bid_start_time', models.DateTimeField()),
                ('initial_bid_close_time', models.DateTimeField()),
                ('bid_close_time', models.DateTimeField()),
                ('forced_close_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('extended', 'Extended'), ('closed', 'Closed'), ('force_closed', 'Force Closed')], default='draft', max_length=15)),
                ('current_lowest_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rfqs',
                'ordering': ['-created_at'],
            },
        ),
    ]
