# Generated by Django 5.2.12 on 2026-03-28 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionconfig',
            name='rfq',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction_config', to='rfq.rfq'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status'], name='rfqs_status_d3dc61_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['bid_close_time'], name='rfqs_bid_clo_6a5a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['forced_close_time'], name='rfqs_forced__0880ff_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['buyer'], name='rfqs_buyer_i_57fb67_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['is_deleted'], name='rfqs_is_dele_8cfddc_idx'),
        ),
        migrations.AddConstraint(
            model_name='rfq',
            constraint=models.CheckConstraint(condition=models.Q(('forced_close_time__gt', models.F('bid_close_time'))), name='rfq_forced_close_after_bid_close'),
        ),
        migrations.AddConstraint(
            model_name='rfq',
            constraint=models.CheckConstraint(condition=models.Q(('bid_close_time__gt', models.F('bid_start_time'))), name='rfq_bid_close_after_start'),
        ),
    ]
