# Generated by Django 5.2.12 on 2026-03-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BID_SUBMITTED', 'Bid Submitted'), ('AUCTION_EXTENDED', 'Auction Extended'), ('AUCTION_STARTED', 'Auction Started'), ('AUCTION_CLOSED', 'Auction Closed'), ('AUCTION_FORCE_CLOSED', 'Auction Force Closed'), ('RANK_CHANGED', 'Rank Changed'), ('L1_CHANGED', 'L1 Changed')], max_length=30)),
                ('message', models.TextField()),
                ('old_close_time', models.DateTimeField(blank=True, null=True)),
                ('new_close_time', models.DateTimeField(blank=True, null=True)),
                ('trigger_type_used', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='bids.bid')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
