# Generated by Django 5.2.12 on 2026-03-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='rfq.rfq'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['rfq', 'created_at'], name='activity_lo_rfq_id_039388_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['event_type'], name='activity_lo_event_t_dca05e_idx'),
        ),
    ]
