# Generated by Django 5.2.12 on 2026-03-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='rfq.rfq'),
        ),
    ]
