# Generated by Django 5.2.12 on 2026-03-28 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'role': 'supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['rfq', 'total_amount'], name='bids_rfq_id_88cfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['rfq', 'created_at'], name='bids_rfq_id_ab2287_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['supplier'], name='bids_supplie_26a237_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['is_deleted'], name='bids_is_dele_0e022b_idx'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='bid_total_amount_positive'),
        ),
    ]
